version: '3.7'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: personal_website_dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    container_name: personal_website_database_dev
    networks:
      - main

  web_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: personal_website_web_dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_PORT: ${APP_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      APP_HOSTNAME: ${APP_HOSTNAME}
      ADMIN_PASS_HASH: ${ADMIN_PASS_HASH}
    volumes:
      - .:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    command: sleep infinity
    depends_on:
      - database
    container_name: personal_website_web_dev
    networks:
      main:
        aliases:
          - web

volumes:
  pgdata_dev:

networks:
  main:
