version: '3.7'

services:
  database:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: personal_website_prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    container_name: personal_website_database_prod
    networks:
      - main

  web_prod:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.prod
    # image: personal_website_web_prod
    image: pizzapim/personal_website:latest
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_PORT: ${APP_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      APP_HOSTNAME: ${APP_HOSTNAME}
      ADMIN_PASS_HASH: ${ADMIN_PASS_HASH}
    depends_on:
      - database
    container_name: personal_website_web_prod
    networks:
      main:
        aliases:
          - web

volumes:
  pgdata_prod:

networks:
  main:
