version: '3.7'

services:
  ouroboros:
    container_name: personal_website_ouroboros
    image: pyouroboros/ouroboros
    environment:
      CLEANUP: "true"
      INTERVAL: 300
      LOG_LEVEL: info
      SELF_UPDATE: "true"
      MONITOR: personal_website_web_prod
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/root/.docker/config.json

  database:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: personal_website_prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    container_name: personal_website_database_prod
    networks:
      - main

  web_prod:
    image: pizzapim/personal_website:latest
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_PORT: ${APP_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      APP_HOSTNAME: ${APP_HOSTNAME}
      ADMIN_PASS: ${ADMIN_PASS}
    depends_on:
      - database
    container_name: personal_website_web_prod
    networks:
      main:
        aliases:
          - web
    volumes:
      - picture_uploads:./home/app/uploads

volumes:
  pgdata_prod:
  picture_uploads:

networks:
  main:
